### PR TITLE
Remove websites that redirect off of roboring

### PR DESCRIPTION
**Pull request by TheGreenSquare**
Really annoying to deal with when I can't do shit about it. Not everyone has total control over what web browser they can use and switching to another one just to view some random user's page is annoying.

### CODE REVIEW

**Comment by querkmachine** [comment]
To clarify, if you visit either one of these sites in Google Chrome or a Chromium derivative browser (Edge, Opera, Arc, etc.), you are automatically redirected to a different website prompting you to download a different browser.

**Comment by nellePoint** [comment]
i feel like personal websites have the right to express themselves, this is a form of activism, which should not be suppressed imo.

i also feel like if this is something that really is a problem, users that are "offenders" should be warned and suggested to change the behavior of their sites before just outright removing them.

as well as specifically, [this site](https://lavenderfield.xyz/oops/) and [this site](https://nelle.observer) dont redirect off-site.

[.](https://ouroboros.gay/notes/9w0aeoquncxwvnhi)

**Comment by querkmachine** [comment]
Oh I wasn't advocating for their removal from the ring, just clarifying the conditional behaviour of the redirection as it wasn't clear in the original message.

**Comment by ShadowJonathan** [comment]
lol. lmao.

**Comment by ijomeli** [comment]
for what its worth i have now addressed this complaint and my site no longer redirects off-site, so the chain integrity is maintained even if you are using a weak web browser

**Pull request closed without merging**
